	db MEW; 151

	db 100, 100, 100, 100, 100, 100
	; hp atk def spd sat sdf

	db PSYCHIC_TYPE, PSYCHIC_TYPE ; type
	db 45 ; catch rate
	db 64 ; base exp
	db NO_ITEM, NO_ITEM ; items
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/mew/front.dimensions"
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_MEDIUM_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm RETURN, HIDDEN_POWER, FIRE_PUNCH, ICE_PUNCH, THUNDERPUNCH, SWORDS_DANCE, CUT, FLY, HEADBUTT, BODY_SLAM, TAKE_DOWN, ROAR, FLAMETHROWER, SURF, ICE_BEAM, BLIZZARD, HYPER_BEAM, COUNTER, SEISMIC_TOSS, STRENGTH, MEGA_DRAIN, PETAL_DANCE, THUNDERBOLT, THUNDER_WAVE, THUNDER, ROCK_THROW, EARTHQUAKE, HYPER_VOICE, DIG, TOXIC, PSYCHIC_M, HYPNOSIS, MEDITATE, MIMIC, LIGHT_SCREEN, REFLECT, FIRE_BLAST, WATERFALL, SWIFT, SKY_ATTACK, FLASH, EXPLOSION, REST, ROCK_SLIDE, SUBSTITUTE, THIEF, ACID_JET, REVERSAL, PROTECT, SLUDGE_BOMB, ICY_WIND, OUTRAGE, SANDSTORM, GIGA_DRAIN, ENDURE, SWAGGER, SPARK, FURY_CUTTER, SLEEP_TALK, HEAL_BELL, PURSUIT, IRON_TAIL, TWISTER, RAIN_DANCE, SUNNY_DAY, SHADOW_BALL
	; end
