	db MEWTWO; 150

	db 106, 110, 90, 130, 154, 90
	; hp atk def spd sat sdf

	db PSYCHIC_TYPE, PSYCHIC_TYPE ; type
	db 3 ; catch rate
	db 220 ; base exp
	db BERSERK_GENE, BERSERK_GENE ; items
	db GENDER_UNKNOWN ; gender ratio
	db 100 ; unknown 1
	db 120 ; step cycles to hatch
	db 5 ; unknown 2
	INCBIN "gfx/pokemon/mewtwo/front.dimensions"
	dw NULL, NULL ; unused (beta front/back pics)
	db GROWTH_SLOW ; growth rate
	dn EGG_NONE, EGG_NONE ; egg groups

	; tm/hm learnset
	tmhm RETURN, HIDDEN_POWER, FIRE_PUNCH, ICE_PUNCH, THUNDERPUNCH, SWORDS_DANCE, CUT, FLY, HEADBUTT, BODY_SLAM, TAKE_DOWN, FLAMETHROWER, SURF, ICE_BEAM, BLIZZARD, HYPER_BEAM, COUNTER, SEISMIC_TOSS, STRENGTH, MEGA_DRAIN, THUNDERBOLT, THUNDER_WAVE, THUNDER, ROCK_THROW, EARTHQUAKE, PSYCHIC_M, MIMIC, LIGHT_SCREEN, REFLECT, FIRE_BLAST, SWIFT, FLASH, EXPLOSION, ROCK_SLIDE, SUBSTITUTE, REVERSAL, PROTECT, ICY_WIND, OUTRAGE, GIGA_DRAIN, ENDURE, SWAGGER, SPARK, SLEEP_TALK, PURSUIT, TWISTER, RAIN_DANCE, SUNNY_DAY, SHADOW_BALL, ROCK_SMASH, WHIRLPOOL
	; end
