; attacks learned when evolving

EvolutionMoves::
	db NO_MOVE
	db NO_MOVE
	db BODY_SLAM	; venusaur
	db NO_MOVE
	db NO_MOVE
	db WING_ATTACK	; charizard
	db NO_MOVE
	db NO_MOVE
	db LOCK_ON	; BLASTOISE
	db NO_MOVE
	db HARDEN	; METAPOD
	db GUST		; BUTTERFREE
	db NO_MOVE
	db HARDEN	; KAKUNA
	db FURY_ATTACK	; BEEDRILL
	db NO_MOVE
	db NO_MOVE
	db NO_MOVE	; PIDGEOT
	db NO_MOVE
	db SCARY_FACE	; RATICATE
	db NO_MOVE
	db SCARY_FACE	; FEAROW
	db NO_MOVE
	db SCARY_FACE	; ARBOK
	db NO_MOVE
	db NO_MOVE	; RAICHU
	db NO_MOVE
	db NO_MOVE	; SANDSLASH
	db NO_MOVE
	db NO_MOVE
	db DOUBLE_KICK	; NIDOQUEEN
	db NO_MOVE
	db NO_MOVE
	db DOUBLE_KICK	; NIDOKING
	db NO_MOVE
	db NO_MOVE	; CLEFABLE
	db NO_MOVE
	db CONFUSION	; NINETALES
	db NO_MOVE
	db NO_MOVE	; WIGGLYTUFF
	db NO_MOVE
	db LICK		; GOLBAT
	db NO_MOVE
	db SWAGGER	; GLOOM
	db HAZE		; VILEPLUME
	db NO_MOVE
	db WITHDRAW	; PARASECT
	db NO_MOVE
	db SILVER_WIND	; VENOMOTH
	db NO_MOVE
	db TRI_ATTACK	; DUGTRIO
	db NO_MOVE
	db NO_MOVE	; PERSIAN
	db NO_MOVE
	db SCARY_FACE	; GOLDUCK
	db NO_MOVE
	db NO_MOVE	; PRIMEAPE
	db NO_MOVE
	db SCARY_FACE	; ARCANINE
	db NO_MOVE
	db NO_MOVE
	db FOCUS_ENERGY	; POLIWRATH
	db NO_MOVE
	db CONFUSION	; KADABRA
	db NO_MOVE
	db NO_MOVE
	db VITAL_THROW	; MACHOKE
	db COMET_PUNCH	; MACHAMP
	db NO_MOVE
	db DISABLE	; WEEPINBELL
	db POISON_FANG	; VICTREEBEL
	db NO_MOVE
	db POISON_FANG	; TENTACRUEL
	db NO_MOVE
	db NO_MOVE
	db SCARY_FACE	; GOLEM
	db NO_MOVE
	db HORN_ATTACK	; RAPIDASH
	db NO_MOVE
	db WITHDRAW	; SLOWBRO
	db NO_MOVE
	db TRI_ATTACK	; MAGNETON
	db NO_MOVE	; FARFETCHD
	db NO_MOVE
	db TRI_ATTACK	; DODRIO
	db NO_MOVE
	db HORN_ATTACK	; DEWGONG
	db NO_MOVE
	db NO_MOVE	; MUK
	db NO_MOVE
	db SPIKE_CANNON	; CLOYSTER
	db NO_MOVE
	db NO_MOVE
	db LOCK_ON	; GENGAR
	db NO_MOVE	; ONIX
	db NO_MOVE
	db MEDITATE	; HYPNO
	db NO_MOVE
	db STOMP	; KINGLER
	db NO_MOVE
	db NO_MOVE	; ELECTRODE
	db NO_MOVE
	db STOMP	; EXEGGUTOR
	db NO_MOVE
	db SLASH	; MAROWAK
	db DOUBLE_KICK	; HITMONLEE
	db DIZZY_PUNCH	; HITMONCHAN
	db NO_MOVE	; LICKITUNG
	db NO_MOVE
	db NO_MOVE	; WEEZING
	db NO_MOVE
	db NO_MOVE	; RHYDON
	db NO_MOVE	; CHANSEY
	db NO_MOVE	; TANGELA
	db NO_MOVE	; KANGASKHAN
	db NO_MOVE
	db POISON_STING	; SEADRA
	db NO_MOVE
	db ANCIENTPOWER	; SEAKING
	db NO_MOVE
	db PSYBEAM	; STARMIE
	db NO_MOVE	; MRMIME
	db NO_MOVE	; SCYTHER
	db SCARY_FACE	; JYNX
	db SCARY_FACE	; ELECTABUZZ
	db SCARY_FACE	; MAGMAR
	db NO_MOVE	; PINSIR
	db NO_MOVE	; TAUROS
	db NO_MOVE	
	db BITE		; GYARADOS
	db NO_MOVE	; LAPRAS
	db NO_MOVE	; DITTO
	db NO_MOVE
	db WATER_GUN	; VAPOREON
	db THUNDERSHOCK	; JOLTEON
	db EMBER	; FLAREON
	db NO_MOVE	; PORYGON
	db NO_MOVE
	db SPIKE_CANNON	; OMASTAR
	db NO_MOVE
	db SLASH	; KABUTOPS
	db NO_MOVE	; AERODACTYL
	db NO_MOVE	; SNORLAX
	db NO_MOVE	; ARTICUNO
	db NO_MOVE	; ZAPDOS
	db NO_MOVE	; MOLTRES
	db NO_MOVE
	db AURORA_BEAM	; DRAGONAIR
	db WING_ATTACK	; DRAGONITE
	db NO_MOVE	; MEWTWO
	db NO_MOVE	; MEW
	db NO_MOVE
	db NO_MOVE
	db MEGA_DRAIN	; MEGANIUM
	db NO_MOVE
	db NO_MOVE
	db FOCUS_ENERGY	; TYPHLOSION
	db NO_MOVE
	db NO_MOVE
	db FAINT_ATTACK	; FERALIGATR
	db NO_MOVE
	db DEFENSE_CURL	; FURRET
	db NO_MOVE
	db WING_ATTACK	; NOCTOWL
	db NO_MOVE
	db SAFEGUARD	; LEDIAN
	db NO_MOVE
	db FOCUS_ENERGY	; ARIADOS
	db MOONLIGHT	; CROBAT
	db NO_MOVE
	db NO_MOVE	; LANTURN
	db NO_MOVE	; PICHU
	db NO_MOVE	; CLEFFA
	db NO_MOVE	; IGGLYBUFF
	db NO_MOVE
	db SILVER_WIND	; TOGETIC
	db NO_MOVE
	db MEDITATE	; XATU
	db NO_MOVE
	db NO_MOVE
	db THUNDERPUNCH	; AMPHAROS
	db RAPID_SPIN	; BELLOSSOM
	db NO_MOVE
	db NO_MOVE	; AZUMARILL
	db NO_MOVE	; SUDOWOODO
	db SING		; POLITOED
	db NO_MOVE
	db NO_MOVE
	db COTTON_SPORE	; JUMPLUFF
	db NO_MOVE	; AIPOM
	db NO_MOVE
	db RAZOR_LEAF	; SUNFLORA
	db NO_MOVE	; YANMA
	db NO_MOVE
	db AMNESIA	; QUAGSIRE
	db CONFUSION	; ESPEON
	db PURSUIT	; UMBREON
	db NO_MOVE	; MURKROW
	db MEDITATE	; SLOWKING
	db NO_MOVE	; MISDREAVUS
	db NO_MOVE	; UNOWN
	db NO_MOVE	; WOBBUFFET
	db NO_MOVE	; GIRAFARIG
	db NO_MOVE
	db METALSCREECH	; FORRETRESS
	db NO_MOVE	; DUNSPARSE
	db NO_MOVE	; GLIGAR
	db ROAR		; STEELIX
	db NO_MOVE
	db HYPER_FANG	; GRANBULL
	db NO_MOVE	; QWILFISH
	db METAL_CLAW	; SCIZOR
	db NO_MOVE	; SHUCKLE
	db NO_MOVE	; HERACROSS
	db NO_MOVE	; SNEASEL
	db NO_MOVE
	db BITE		; URSARING
	db NO_MOVE
	db PROTECT	; MAGCARGO
	db NO_MOVE
	db HYPER_FANG	; PILOSWINE
	db NO_MOVE	; CORSOLA
	db NO_MOVE
	db OCTAZOOKA	; OCTILLERY
	db NO_MOVE	; DELIBIRD
	db NO_MOVE	; MANTINE
	db NO_MOVE	; SKARMORY
	db NO_MOVE
	db CURSE	; HOUNDOOM
	db DRAGON_RAGE	; KINGDRA
	db NO_MOVE
	db HORN_ATTACK	; DONPHAN
	db CONVERSION2	; PORYGON2
	db NO_MOVE	; STANTLER
	db NO_MOVE	; SMEARGLE
	db NO_MOVE
	db RAPID_SPIN	; HITMONTOP
	db NO_MOVE	; SMOOCHUM
	db NO_MOVE	; ELEKID
	db NO_MOVE	; MAGBY
	db NO_MOVE	; MILTANK
	db NO_MOVE	; BLISSEY
	db NO_MOVE	; RAIKOU
	db NO_MOVE	; ENTEI
	db NO_MOVE	; SUICUNE
	db NO_MOVE
	db HARDEN	; PUPITAR
	db THRASH	; TYRANITAR
	db NO_MOVE	; LUGIA
	db NO_MOVE	; HO-OH
	db NO_MOVE	; CELEBI
